# Generated by Django 4.2.1 on 2023-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TbTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('szFileName', models.CharField(blank=True, db_index=True, default='.jinja2', help_text="Имя файла шаблона (расширение .jinja2 или .html)<br/><b style='color:red'>ПОДУМАЙТЕ ПЕРЕД ТЕМ КАК ИЗМЕНЯТЬ!!</b>", max_length=100, null=True, unique=True, verbose_name='Файл Шаблона')),
                ('szJinjaCode', models.TextField(blank=True, default='', help_text='Код шаблона (jinja2)', null=True, verbose_name='Шаблон')),
                ('szDescription', models.CharField(max_length=100, verbose_name='Описание')),
                ('szVar', models.CharField(blank=True, default='var', max_length=16, null=True, verbose_name='Переменная')),
            ],
            options={
                'verbose_name': '[…Шаблон] Ⓣ',
                'verbose_name_plural': '[…Шаблоны] Ⓣ',
            },
        ),
    ]
